bitrise-io/osx-box-bootstrap

playbook.yml

As ReactNative has been gaining a massive amount of popularity, I think it would be a good idea to include their needed tools `watchman` and `flow` for increased build speed

Install flow & watchman by default for ReactNative

---

profiles/bashrc

if `set -e` is enabled the one liner fails!

use full, non one liner if syntax, or else source can fail

---

playbook.yml

Ruby 2.4 broke pretty much all the popular Ruby CLI tools

Use homebrew/versions/ruby23 (ruby 2.3.x) for now

---

CHANGELOG.md
profiles/bitrise_profile
system_report.sh
xamarin-playbook.yml

Installation of .Net Core right now is still a bit "beta", we'll consider pre-installing .Net Core
in the future again once it lands in `brew`. Until that it's way more flexible to use a Step
instead, which can be updated any time, instead of sticking to a preinstalled version
which is hard & slow to change.
Related discussion: https://github.com/bitrise-io/osx-box-bootstrap/pull/44

v2017_05_02_1 - remove preinstalled dotNet Core

---

playbook.yml

Bundler is a dependency of rubygems (since rubygems 2.7.x), manually running `gem install bundler` hangs the playbook for ever so we leave the default as of now.

Remove explicit bundler install

---

playbook.yml

Without this Xcode.app might block UI Tests,
waiting for manual input (password). Since Xcode 9.3 it seems this is
the only way to accept the permissions required for iOS UI Tests,
if you only accept it via the GUI that won't persist after an OS reboot,
but running this command will.
Before Xcode 9.3 it was enough to accept this via the GUI only once,
but this seem to be changed in Xcode 9.3 (final).

run `sudo DevToolsSecurity -enable` during provisioning

---

java-android-playbook.yml
roles/android/defaults/main.yml
roles/java/defaults/main.yml
roles/java/tasks/main.yml
roles/jenv/tasks/main.yml
roles/jenv/templates/patch.j2
roles/patch_bashrc/tasks/main.yml
roles/patch_bashrc/templates/patch.j2
roles/tools/tasks/main.yml
xamarin-playbook.yml

We cannot install OracleJDK from brew anymore because Oracle & Java licensing changes. This PR is for switching to an AdoptOpenJDK packaged version.

Fix java install

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

We no longer have any stacks with CocoaPods <1.0 installed, even Xcode 8.3 stack has 1.2.1 on it https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-8.3.x.log#L64

Removing deprecated cocoapods version (<1.0) related weekly update

---

CHANGELOG.md
roles/intermediate-setup/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml
system_report.sh

The Firebase CLI ([GitHub](https://github.com/firebase/firebase-tools)) provides a variety of tools for managing, viewing, and deploying to Firebase projects.
Add support for Firebase CLI - https://firebase.google.com/docs/app-distribution/ios/distribute-cli

Add support for Firebase CLI

---

CHANGELOG.md
roles/intermediate-setup/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

fix swift-sh brew install path, install on Xcode 9+

---

bitrise.yml

[IN-0] remove vagrant-setup, the playbook has been deleted in mid 2019

---

roles/intermediate-setup/tasks/main.yml
roles/weekly-update-shared/tasks/main.yml

[Tool-2251] Add Go isntall to weekly update

---

playbook.yml
roles/ruby/tasks/ruby.yml

[IN-1551] Remove Ruby from base builder creation, and remove quickfix

---

roles/profiles/files/bashrc
system_report.sh

[IN-1560] we don't use the .sh extension under profile.d follow it up in bashrc

---

CHANGELOG.md
roles/flutter/defaults/main.yml
roles/profiles/files/bitrise_profile

We would like to upgrade Flutter SDK to the latest stable version.
- [Flutter SDK releases](https://flutter.dev/docs/development/tools/sdk/releases)
- [Changelog 1.20.2](https://github.com/flutter/flutter/releases/tag/1.20.2)

Upgrade Flutter SDK to 1.20.2

---

roles/android/tasks/main.yml
roles/android/templates/patch.j2
roles/java/tasks/main.yml
roles/jenv/tasks/main.yml

Currently, gradle breaks with this version. We must upgrade next week.
Reverted PR: 
- https://github.com/bitrise-io/osx-box-bootstrap/commit/5290c50d
- https://github.com/bitrise-io/osx-box-bootstrap/pull/293

[IN-1719]: revert java 11 0 upgrade to not break gradle

---

_scripts/install_molecule_dependencies.sh
ansible-lint.yaml
bitrise.yml

[IN-1877] Install python3.8, molecule breaks on python3.5

---

roles/java/tasks/main.yml

[IN-0] bugfix when brew command not found

---

CHANGELOG.md
roles/flutter/defaults/main.yml
roles/flutter/tasks/main.yml
roles/flutter/tests/test_flutter.py
roles/profiles/files/bitrise_profile

We would like to upgrade Flutter SDK to the latest stable version.
- [Flutter SDK releases](https://flutter.dev/docs/development/tools/sdk/releases)
- Changelog
- [1.20.4](https://github.com/flutter/flutter/releases/tag/1.20.4)
- [1.22.0](https://github.com/flutter/flutter/releases/tag/1.22.0)
- [1.22.1](https://github.com/flutter/flutter/releases/tag/1.22.1)

[IN-2083] Upgrade Flutter SDK to 1.22.1

---

CHANGELOG.md
roles/install-xcode/defaults/main.yml
roles/profiles/files/bitrise_profile

[IN-2172] Switch Xcode to 12.1.1

---

CHANGELOG.md
roles/brew-cleanup-weekly/tasks/main.yml
roles/profiles/files/bashrc
roles/profiles/files/bitrise_profile
roles/profiles/files/zshrc
roles/weekly-update-shared/tasks/main.yml

[IN-2117] disable homebrew install cleanup

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ruby-gems/tasks/main.yml
roles/weekly-update-shared/tasks/main.yml

[IN-2270] cocoapods 1.8 and up defaults to CDN

---

CHANGELOG.md
roles/ruby-gems/tasks/main.yml
roles/weekly-update-shared/tasks/main.yml

This reverts commit 3550c3038239d55fc1d44312d72b3f36a94d17ae.

[IN-0]: Revert "[IN-2270] cocoapods 1.8 and up defaults to CDN (#348)"

---

roles/xcode/files/enable_accessibility.sh

[IN-0] test for newer catalina to set accessibility correctly

---

roles/android/tasks/sdk-install.yml

[IN-0] check if Android SDK is installed before taking a try

---

roles/baseos/tasks/main.yml

[IN-2474] place the ssh pub key on the remote build artifact

---

CHANGELOG.md
roles/android/tasks/sdk-install.yml
roles/profiles/files/bitrise_profile

[IN-2506] android package names have ; in them, handle failures

---

CHANGELOG.md
roles/brew-repos-fix/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-2516]: fix python3 brew link and update changelog and revision id

---

CHANGELOG.md
roles/flutter/defaults/main.yml
roles/flutter/tasks/main.yml
roles/flutter/tests/test_flutter.py
roles/profiles/files/bitrise_profile

We would like to upgrade Flutter SDK to the latest stable version.
- [Flutter SDK releases](https://flutter.dev/docs/development/tools/sdk/releases)
- Changelog
- [1.22.2](https://github.com/flutter/flutter/releases/tag/1.22.2)
- [1.22.3](https://github.com/flutter/flutter/releases/tag/1.22.3)
- [1.22.4](https://github.com/flutter/flutter/releases/tag/1.22.4)
- [1.22.5](https://github.com/flutter/flutter/releases/tag/1.22.5)
- [1.22.6](https://github.com/flutter/flutter/releases/tag/1.22.6)
are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more …

Upgrade Flutter SDK to 1.22.6

---

CHANGELOG.md
CODEOWNERS
roles/profiles/files/bitrise_profile

[IN-2522] update codeowners to reference teams

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ruby-gems/tasks/main.yml

[IN-2544] fix the logic to updates cocoapods unless CI run

---

CHANGELOG.md
roles/go/tasks/main.yml
roles/go/tests/test_go.py
roles/profiles/files/bashrc
roles/profiles/files/bitrise_profile
roles/profiles/files/zshrc

The package installs the Go distribution to /usr/local/go. The package should put the /usr/local/go/bin directory in your PATH environment variable. You may need to restart any open Terminal sessions for the change to take effect.
https://golang.org/doc/install

[IN-2559] Install Go to /usr/local/go as the official documantation says

---

CHANGELOG.md
roles/go/tasks/main.yml
roles/go/tests/test_go.py
roles/profiles/files/bitrise_profile
roles/profiles/files/zshrc

[IN-2559] Revert go install to brew, with a minor version fix

---

CHANGELOG.md
roles/profiles/files/bashrc
roles/profiles/files/bitrise_profile
roles/profiles/files/zshrc

[IN-2567] Make sure xamarin_profile gets sourced last if its there

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/xamarin/files/xamarin_profile

[IN-2552] Add ANDROID_SDK_ROOT in xamarin_profile

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/spotlight/tasks/main.yml

[IN-2562] Remove _catalina from registered value

---

CHANGELOG.md
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile
roles/xcode/files/enable_accessibility.sh
roles/xcode/tasks/main.yml

- [IN-2473] (xcode) debug logs and robust xcode selection
- metadatas
I have added some debug loggin so we can see in the Ansible output what version and build ID Xcode is installed
I took the opportunity to make better use of xcversion and xcode-select to ensure the environment is setup
correctly for developers
[IN-2473]: https://bitrise.atlassian.net/browse/IN-2473

[IN-2473] (xcode) debug logs and robust xcode selection

---

06.baseStack-playbook.yml
CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/simulators/tasks/main.yml

[IN-2598] Init simulators as vagrant, not root

---

roles/ssh-setup/templates/etc/ssh/sshd_config.j2

By default, SSH enables some weak cipher suites. Let's disable them (by enabling only the "strong" algos) to comly with [Bitrise Encryption Policy](https://bitrise.atlassian.net/wiki/spaces/SEC/pages/1391722649/Bitrise+Encryption+Policy).

Disable weak SSH ciphers

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/simulators/vars/12.5.yml

[IN-2638]: revert ios 14.5 from 12.5.x

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/tools-from-artifacts.yml

[IN-2762] fix xcbeautify version call

---

CHANGELOG.md
roles/baseos/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-2797] feat(disksleep): turn off disksleep

---

CHANGELOG.md
roles/bitrise-den/defaults/main.yml
roles/profiles/files/bitrise_profile

[IN-2823] chore(bitrise-den): update agent to 1.30.1

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
system_report.sh

[IN-3566] Added groovy version info to the preinstalled tools
