playbook.yml
system_report.sh

This take 30+ minutes to install on the machine. Bad choke point.

Add homebrewed wine package

---

CHANGELOG.md
profiles/bitrise_profile
system_report.sh
weekly-cache-update-playbook.yml

`v2016_08_10_1` - Bitrise CLI 1.3.7

---

system_report.sh

List all Ruby gems in system report

---

system_report.sh

imagemagick - typo fix

---

xamarin-playbook.yml

ensure debug.keystore

---

playbook.yml
profiles/bashrc
profiles/tools_profile
system_report.sh
weekly-cache-update-playbook.yml

export MATCH_KEYCHAIN_PASSWORD

---

xamarin-playbook.yml

the `extra-android-support` Android package was removed, it's no longer available

Xamarin: extra-android-support removed

---

playbook.yml
system_report.sh

preinstall ionic and cordova npm (CLI) packages

---

playbook.yml
system_report.sh

Preinstall yarn

---

playbook.yml

Add "gem update --system" back again - should work with the default brew installed ruby now

---

system_report.sh
xamarin-playbook.yml

Add .net core support to Xamarin box

---

profiles/xamarin_profile

Speed up .net core builds on first launch

---

playbook.yml
system_report.sh

We're exited to use your product! This change is fundamental to how we work (a mono repo with docker and iOS builds).
https://discuss.bitrise.io/t/how-to-use-your-own-docker-image-for-your-builds/69
https://github.com/bitrise-io/osx-box-bootstrap/issues/40

adding docker to image

---

playbook.yml
system_report.sh

Reverts bitrise-io/osx-box-bootstrap#47

Revert "adding docker to image"

---

README.md
profiles/xamarin_profile
system_report.sh

migrate to Visual Studio for xamarin projects

---

CHANGELOG.md
playbook.yml
profiles/bitrise_profile
system_report.sh

Allows connectivity using strong cryptography.

jce-unlimited-strength-policy preinstalled cask added

---

system_report.sh

Fix system_report.sh

---

CHANGELOG.md
profiles/bitrise_profile
weekly-cache-update-playbook.yml

Update bitrise CLI to 1.9.0

---

CHANGELOG.md
playbook.yml
profiles/bitrise_profile
setupfiles/box-info.json.template

Remove unused box-info.json

---

CHANGELOG.md
playbook.yml
profiles/bitrise_profile
system_report.sh

Remove jce-unlimited-strength-policy cask (#55)

---

xamarin-playbook.yml

Android tools v26

---

xamarin-playbook.yml

Sdkmanager platform-tools

---

CHANGELOG.md
profiles/bitrise_profile
xamarin-playbook.yml

Downgrade to Java 8

---

CHANGELOG.md
profiles/bitrise_profile

Version v2018_01_04_1

---

system_report.sh

print Android NDK version

---

playbook.yml

https://app.clickup.com/757956/762238/t/4pdn0

Fix: Node 8 LTS was added to the PATH

---

CHANGELOG.md
profiles/bitrise_profile
weekly-cache-update-playbook.yml

bitrise cli update to 1.23

---

CHANGELOG.md
profiles/bashrc
profiles/bitrise_profile

Remove ulimit directive

---

CHANGELOG.md
profiles/bitrise_profile

Changelog baskfill for Java playbook

---

system_report.sh

Separate Android block in system_report.sh

---

playbook.yml

This change needed because **npm install -g ionic cordova** with Node8 has broke the build (with npm ERR! code EISDIR), but it has passed with Node10 without any issue.

Upgraded NodeJS from 8.x to 10.x

---

CHANGELOG.md
profiles/bitrise_profile

CHANGELOG.md updated with NodeJS upgrade

---

CHANGELOG.md
profiles/bitrise_profile
weekly-cache-update-playbook.yml

Update Bitrise CLI to 1.27.1

---

CHANGELOG.md
java-android-playbook.yml
profiles/bitrise_profile
roles/android/tasks/main.yml

Install Android SDK from brew

---

CHANGELOG.md
weekly-cache-update-playbook.yml

Change guide link

---

CHANGELOG.md
profiles/bitrise_profile
setupfiles/bootstrap_remote_access.sh.tmpl
weekly-cache-update-playbook.yml

osx remote access config

---

CHANGELOG.md
java-android-playbook.yml
profiles/bitrise_profile
roles/flutter/tasks/main.yml
system_report.sh
weekly-cache-update-playbook.yml
xamarin-playbook.yml

install flutter from brew

---

roles/flutter/tasks/main.yml
roles/jenv/tasks/main.yml
roles/patch_bashrc/tasks/main.yml

Fix profiles in the weekly update playbooks

---

roles/flutter/tasks/main.yml
roles/jenv/tasks/main.yml
roles/patch_bashrc/tasks/main.yml

Fix profile fix permission

---

setupfiles/bootstrap_remote_access.sh.tmpl

Enable vnc

---

setupfiles/bootstrap_remote_access.sh.tmpl

uncomment vnc-server ngrok tunnel

---

roles/flutter/defaults/main.yml

casually update flutter to latest version 1.6.5

update to 1.6.5

---

weekly-cache-update-playbook.yml

update to 1.32.0

---

roles/flutter/defaults/main.yml

This Pull Request upgrades Flutter version.
https://flutter.dev/docs/development/tools/sdk/releases
This Pull Request does not add a tool, just upgrading existing Flutter version.

Upgrade Flutter version to latest stable

---

roles/flutter/defaults/main.yml

This Pull Request upgrades Flutter version to latest stable.
* https://flutter.dev/docs/development/tools/sdk/releases
* https://github.com/flutter/flutter/releases/tag/v1.7.8%2Bhotfix.4
This Pull Request does not add a tool, just upgrading existing Flutter version.

Upgrade Flutter version to 1.7.8+hotfix.4

---

CHANGELOG.md
roles/android/defaults/main.yml
roles/flutter/defaults/main.yml

flutter v1.9.1+hotfix.2, NDK r20

---

roles/android-apk-tools/tasks/main.yml

Fixing aapt2 unzip

---

CHANGELOG.md

updated changelog with the previous ruby update

---

system_report.sh

Fix Flutter version report

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

Bitrise CLI update to 1.35.0

---

CHANGELOG.md
roles/intermediate-setup/tasks/main.yml

Just another victim of rbenv

---

roles/intermediate-setup/tasks/main.yml

downgrade of 2.4

---

roles/intermediate-setup/tasks/main.yml

these versions work finally

---

roles/system-report/tasks/main.yml

Fix indentation in debug msg

---

roles/system-report/tasks/main.yml

There was a missing / in path, so the builds did not find the file

---

roles/system-report/tasks/main.yml

disabled become, and added ignore error to the task

---

system_report.sh

Remove bundletool from system report

---

CHANGELOG.md
system_report.sh

Remove bundletool system

---

PULL_REQUEST_TEMPLATE.md

I have added two more steps to the PR template:
- Add revision ID to CHANGELOG.md
- Change the revision ID in bitrise_profile

PR Template updated

---

CHANGELOG.md
roles/flutter/defaults/main.yml
roles/profiles/files/bitrise_profile

This Pull Request upgrades Flutter version to latest stable.
* https://flutter.dev/docs/development/tools/sdk/releases
* Changelogs
* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.3
* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.4
* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.5
* https://github.com/flutter/flutter/releases/tag/v1.9.1%2Bhotfix.6

Upgrade Flutter version to 1.9.1+hotfix.6

---

CHANGELOG.md
PULL_REQUEST_TEMPLATE.md
roles/intermediate-setup/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

CocoaPods bugfix in-630

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

- [* ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
- [* ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [* ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

Bitrise CLI to 1.36.0

---

CHANGELOG.md
roles/intermediate-setup/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#version-comparison

correct way to compare version strings in ansible

---

CHANGELOG.md
roles/intermediate-setup/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

missing comma in ansible syntax

---

CHANGELOG.md
roles/intermediate-setup/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

quote the when clause, no jinja tempates

---

CHANGELOG.md
roles/android-sdk-packages/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/xamarin/tasks/main.yml
weekly-cache-update-playbook.yml

- [x ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
- [ x] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ x] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ x] I have updated the revisionID in …

Changing ownership for ANDROID_HOME

---

CHANGELOG.md
playbook.yml
roles/profiles/files/bitrise_profile

Ruby 2.6.5 as default ruby (upgrade from 2.6.3)

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

Update Bitrise CLI to 1.37.0

---

CHANGELOG.md
roles/flutter/defaults/main.yml
roles/profiles/files/bitrise_profile

Update flutter stable version

---

CHANGELOG.md
roles/intermediate-setup/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml
system_report.sh

- [ x] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
- [ x] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ x] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ x] I have updated the revisionID in …

[IN-866] removed swift-sh

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

bitrise cli update

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

Updated Bitrise cli to 1.39.0

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

bitrise cli update to 1.39.1

---

CHANGELOG.md
roles/android-sdk-packages/tasks/main.yml
roles/android/defaults/main.yml
roles/flutter/defaults/main.yml
roles/profiles/files/bitrise_profile

Flutter v1.12.13+hotfix.8
NDK r21
build-tools 29.0.3

Update tool versions:

---

roles/intermediate-setup/tasks/main.yml
roles/jenv/tasks/main.yml
roles/weekly-update-shared/tasks/main.yml

fix for 11.4 update

---

bitrise.yml
roles/weekly-update-shared/tasks/main.yml
weekly-cache-update-playbook.yml

Always use the latest cli

---

roles/android-sdk-packages/tasks/main.yml

Remove the sudo install from android sdk

---

CHANGELOG.md
roles/android-sdk-packages/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

- [ x] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
- [ x] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ x] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change

[IN-1192] Explicit install of android platform tools

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
system_report.sh

- [*] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [*] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

Fixed system_report.sh

---

roles/android-sdk-packages/tasks/main.yml
roles/intermediate-setup/tasks/main.yml

[IN-0] starting cmd-bridge server on base builders

---

roles/android-sdk-packages/tasks/main.yml

[IN-1211] Fix fo sdk tools

---

roles/android-sdk-packages/tasks/main.yml
system_report.sh

Fix android-platform-tools

---

roles/android-sdk-packages/tasks/main.yml

[IN-1265] Fix package name

---

CHANGELOG.md
README.md
machine-setup/files/setup.applescript
machine-setup/playbook.yml
roles/android-sdk-packages/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/vs4mac/files/vs4mac-update.applescript
roles/vs4mac/tasks/main.yml
vs4mac.yml

- [x ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
- [x ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

[IN-99] Visual Studio automatic updates

---

bitrise.yml
roles/intermediate-setup/files/ansible.cfg
roles/intermediate-setup/tasks/main.yml

IN-0 add ansible settings to show how long time a task execution takes

---

_scripts/lead_time.sh
bitrise.yml

[IN-1199] Lead time of osx-box

---

CHANGELOG.md
roles/flutter/defaults/main.yml
roles/flutter/tasks/main.yml

IN-1305 update flutter from 1.13+hotfix.8 to 1.17

---

bitrise.yml
roles/intermediate-setup/files/ansible.cfg

In 0 decrease ansible execution time

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml
system_report.sh

added applesimutils and updated system reports

---

roles/node/tasks/main.yml
roles/node/tasks/node.yml

In-1243 move PATH to one layer above

---

CHANGELOG.md
roles/flutter/tasks/main.yml
roles/flutter/templates/patch.j2
roles/profiles/files/bitrise_profile

Flutter path fix

---

roles/android-sdk-packages/tasks/main.yml

[1321] verbose sdk install

---

roles/brew/tasks/main.yml

IN-862 check if brew is installed no matter what the distribution is

---

roles/ssh-setup/tasks/main.yml
roles/ssh-setup/templates/etc/ssh/sshd_config.j2
roles/ssh-setup/tests/test_ssh.py
roles/ssh-setup/tests/test_sshd.py
roles/ssh-setup/vars/debian.yml
roles/ssh-setup/vars/default.yml
roles/ssh-setup/vars/main.yml
roles/tests/molecule/Dockerfile.j2
roles/tests/molecule/ssh-setup/converge.yml
roles/tests/molecule/ssh-setup/molecule.yml
roles/tests/molecule/ssh-setup/tests/test_default.py

are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_~
This is minor refactor, first two points are not applicable, last two will be addressed shortly.

[IN-738] template sshd config

---

roles/ruby/tasks/ruby.yml
roles/weekly-update-shared/tasks/main.yml
weekly-cache-update-playbook.yml

[IN-1550] fix install of cocoapods and weekly cache update

---

weekly-cache-update-playbook.yml

[IN-1507] Install android sdk on all VMs

---

roles/android/defaults/main.yml

[IN-0] AP lvl 30 system images

---

roles/weekly-update-shared/files/bootstrap_remote_access.sh.tmpl

fix sed rule for ssh config

---

system_report.sh

IN-1560 platform-tools can be found under ANDROID_HOME

---

ansible.cfg
bitrise.yml
roles/weekly-update-shared/tasks/main.yml

[IN-1666] Ansible local plugin not found error investigation

---

roles/install-xcode/defaults/main.yml

[IN-1657] Xcode 12.0.4

---

roles/install-xcode/defaults/main.yml

[IN-1730] 12 Beta 5

---

roles/install-xcode/defaults/main.yml

[IN-1744] 12 beta 6

---

roles/jenv/tasks/main.yml

[IN-0]: fix java version in jenv role

---

roles/install-xcode/defaults/main.yml

[IN-1763] added 11.7 beta

---

roles/weekly-update-shared/tasks/main.yml

[IN-0] Homebrew update before install

---

roles/install-xcode/defaults/main.yml

[IN-1813]: use stable instead of beta

---

system_report.sh

[IN-1843] Add new tools to system report

---

roles/android/tasks/main.yml
roles/android/templates/patch.j2

Minor fixes, none of these apply

[IN-0]: Minor android fixes

---

PULL_REQUEST_TEMPLATE.md

[IN-0] Update PR template with tests

---

CHANGELOG.md
roles/flutter/defaults/main.yml
roles/flutter/tasks/main.yml
roles/flutter/tests/test_flutter.py

[IN-0] Upgrade flutter sdk

---

roles/install-xcode/defaults/main.yml

[IN-1938] new day, new beta

---

roles/misc-setup/tasks/main.yml

[IN-2010] Remove redundant Java install

---

roles/java/tasks/main.yml

[IN-2032] Use local repo in case of cask-versions too

---

CHANGELOG.md
roles/install-xcode/defaults/main.yml
roles/profiles/files/bitrise_profile

[IN-0]: switch Xcode to 12.2 Beta 2

---

CHANGELOG.md
roles/certs/tasks/main.yml
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

[IN-0]: fix certs in weeklies

---

roles/brew-repos-fix/files/setup_brew_cask.sh
roles/brew-repos-fix/files/setup_brew_core.sh
roles/certs/tasks/main.yml
roles/java/tasks/main.yml

[IN-2011] fixed core/cask/cask-versions

---

CHANGELOG.md
roles/node/defaults/main.yml
roles/node/tasks/node.yml
roles/profiles/files/bitrise_profile

[IN-2035] npm ionic to latest

---

CHANGELOG.md
roles/node/defaults/main.yml
roles/profiles/files/bitrise_profile
roles/ruby/defaults/main.yml
roles/ruby/tests/test_ruby.py

Will this also update the following image `https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-11.5.x.log` or does that require another PR?

chore(cocoapods): update version

---

CODEOWNERS

[IN-2136] Krisi G is no more

---

roles/brew-cleanup-weekly/tasks/main.yml

[IN-0]: ignore errors on brew cleanup

---

weekly-cache-update-playbook.yml

[IN-2187] Reinstall gems at the beginning so we don't remove other stuff

---

CHANGELOG.md
roles/install-xcode/defaults/main.yml
roles/install-xcode/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/xamarin/tasks/main.yml

[IN-2216] 12.2 release (these were used on a feature branch, creating a PR so it will be in the master)

---

roles/certs/tasks/main.yml

[IN-2190] Runtime, check the error code, so the role is not skipped

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/defaults/main.yml
system_report.sh

[IN-2264] preinstall awscli

---

CHANGELOG.md
playbook.yml
roles/node/defaults/main.yml
roles/profiles/files/bitrise_profile
system_report.sh
weekly-cache-update-playbook.yml

[IN-2319] Update appcenter-cli to 2.7.3

---

CODEOWNERS

[IN-0] Remove Blaise and Kanan 😭

---

roles/node/tasks/node.yml
weekly-cache-update-playbook.yml

[IN-2297] Remove node from weekly cache update

---

roles/ruby-gems/files/ruby_cleanup.sh

[IN-0] remove rogue bundler install, happens in next play

---

_scripts/molecule/requirements.txt

bump version of ansible

---

CHANGELOG.md
roles/java/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/xamarin/tasks/main.yml

[IN-2340] Update brew cask installs

---

roles/java/tasks/main.yml

[IN-0] Adopt version with cask

---

ansible-lint.yaml
roles/enable-auto-login/meta/main.yml
roles/enable-auto-login/tasks/main.yml

yaml linting

---

roles/ssh-setup/defaults/main.yml

[IN-0] set default param_user and param_group for ssh

---

01.baseOS-playbook.yml

[IN-0] required variable for running gen2 base

---

05.baseAndroid-playbook.yml
06.baseStack-playbook.yml
roles/bitrise-den/defaults/main.yml
roles/bitrise-den/tasks/main.yml

[IN-0] pass Github token through to ansible as an Env var

---

ansible-lint.yaml
roles/ruby-gems/tasks/main.yml
roles/weekly-update-shared/tasks/main.yml

[IN-0] sort out the idempotency on cocoapds setup

---

roles/simulators/vars/12.4.yml

[IN-2398] 12.4 simulators list

---

roles/brew/tasks/main.yml

[IN-0] fix failing brew install check

---

roles/xcode/files/enable_accessibility.sh
roles/xcode/tasks/main.yml

[IN-2442] Accessibility TCC database has new schema on Big Sur

---

roles/java/tasks/main.yml
roles/xamarin/tasks/main.yml

[IN-2467] homebrew cask reverts

---

playbook.yml

[IN-2465]: xcode-install follow up

---

roles/ruby/tasks/main.yml

[IN-0] fix ruby test on ubuntu

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/defaults/main.yml
roles/weekly-update-shared/tasks/main.yml
roles/weekly-update-shared/tasks/tools-from-artifacts.yml

- [-] I updated the corresponding tests if there were any.
- [-] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added

[IN-2469] xcbeautify download from GitHub

---

roles/weekly-update-shared/tasks/main.yml
roles/weekly-update-shared/tasks/tools-from-artifacts.yml

[IN-0] xclogparser minor fixes

---

roles/xcode/files/enable_accessibility.sh

IN-2471 output error code for ansible distribution

---

.gitignore
CHANGELOG.md
roles/profiles/files/bitrise_profile

[IN-0]: include vscode in gitignore

---

CHANGELOG.md
bitrise.yml
roles/brew-repos-fix/templates/setup_brew_core.sh.j2
roles/brew-repos-fix/tests/test_brew.py
roles/profiles/files/bitrise_profile
roles/tests/molecule/brew-repos-fix/converge.yml
roles/tests/molecule/brew-repos-fix/molecule.anka.yml
roles/tests/molecule/brew-repos-fix/molecule.docker.yml

[IN-0] brew-repos-fix test fixes

---

CHANGELOG.md
roles/brew-repos-fix/tasks/main.yml
roles/brew-repos-fix/templates/setup_brew_cask.sh.j2
roles/brew-repos-fix/templates/setup_brew_core.sh.j2
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile

[IN-2470]: check homebrew-core and cask for sha

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/defaults/main.yml
system_report.sh

[IN-0]: include cmake in weekly-update-shared

---

CHANGELOG.md
CODEOWNERS
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/defaults/main.yml

[IN-0] Add P Nagy to codeowners

---

CHANGELOG.md
playbook.yml
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/defaults/main.yml

[IN-0] Remove roles from playbook that are not meant to be here

---

06.baseStack-playbook.yml
CHANGELOG.md
roles/profiles/files/bitrise_profile

[IN-2252] param password for vagrant

---

CHANGELOG.md
_scripts/lead_time.sh
bitrise.yml
roles/enable-auto-login/meta/main.yml
roles/profiles/files/bitrise_profile

[IN-2491] Disable KPI slack notification

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/xamarin/defaults/main.yml
roles/xamarin/files/xamarin_profile
roles/xamarin/tasks/main.yml
roles/xamarin/tests/test_xamarin.py

[IN-2533] Fix Nunit path

---

05.baseAndroid-playbook.yml
CHANGELOG.md
roles/profiles/files/bitrise_profile
weekly-cache-update-playbook.yml

[IN-2527] Run and install java-tools without any exception

---

CHANGELOG.md
roles/android/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-2514] This is done in the Xamarin role as it should be

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/simulators/vars/11.6.yml
roles/simulators/vars/11.7.yml
roles/simulators/vars/12.0.yml
roles/simulators/vars/12.1.yml
roles/simulators/vars/12.2.yml
roles/simulators/vars/12.3.yml
roles/simulators/vars/12.4.yml
roles/simulators/vars/12.5.yml

[IN-2540] Fix up simulator lists

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/xcode/tasks/main.yml

[IN-2534] Make sure that ansible finds the executable

---

06.baseStack-playbook.yml
CHANGELOG.md
roles/profiles/files/bitrise_profile

[IN-2514] upgrade den version to v1.20.0

---

CHANGELOG.md
roles/bitrise-cli/tasks/cli-install.yml
roles/bitrise-cli/tasks/main.yml
roles/bitrise-den/tasks/main.yml
roles/go/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-2552] Weekly update fixes

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/xcode/tasks/main.yml

You run it as vagrant and your home is `/Users/vagrant` you run as root and it is `/var/root` and it's breaking

[IN-2551] Change variable so it is the proper one even when we are root

---

CHANGELOG.md
roles/bitrise-den/defaults/main.yml
roles/bitrise-den/tasks/main.yml
roles/profiles/files/bitrise_profile

[SVC-982] upgrade den agent to v1.22.1

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ssh-setup/tasks/main.yml

[IN-2567] generate missing host ssh keys

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/simulators/vars/12.5.yml

[IN-2577] Install iOS 14.5 sim on Xcode 12.5

---

CHANGELOG.md
roles/bitrise-den/defaults/main.yml
roles/bitrise-den/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-2583] jq fix for den

---

CHANGELOG.md
roles/go/tasks/main.yml
roles/profiles/files/bashrc
roles/profiles/files/bitrise_profile
roles/profiles/files/zshrc

[IN-2612] Extended GO variables with export GO111MODULE=auto

---

06.baseStack-playbook.yml
CHANGELOG.md
roles/baseos/tasks/main.yml
roles/profiles/files/bitrise_profile
roles/spotlight/tasks/disable-spotlight.yml
roles/spotlight/tasks/main.yml

[IN-2598]: blocker fixes

---

CHANGELOG.md
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile

[IN-2598] Update homebrew commit sha

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/xcode/defaults/main.yml

[IN-2638]: 12.5 RC1

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

[IN-0]: do not force update brew

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/defaults/main.yml
system_report.sh

[IN-2635] danger swift

---

CHANGELOG.md
roles/brew-repos-fix/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-0] brew update on brew repos fix

---

CHANGELOG.md
roles/brew-repos-fix/tasks/main.yml
roles/profiles/files/bitrise_profile

In 0 brew fix fix

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ruby-gems/defaults/main.yml

[IN-2651] Add xcov and jazzy gems to build env

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ruby-gems/defaults/main.yml
roles/ruby-gems/tests/test_ruby_gems.py

[IN-2608] Update cocoapods to 1.10.1

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/simulators/tasks/install.yml

[IN-2640]: fix xcversion install for sims

---

CHANGELOG.md
roles/bitrise-den/defaults/main.yml
roles/profiles/files/bitrise_profile

[IN-2659] update DEN agent version

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/defaults/main.yml
roles/weekly-update-shared/tasks/main.yml

[IN-2674]: danger swift exclusion

---

06.baseStack-playbook.yml
CHANGELOG.md
roles/profiles/files/bitrise_profile

[IN-2623] fix(flutter): rerun flutter role on last layer

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/weekly-update-shared/tasks/main.yml

[IN-2694]: pip fix

---

CHANGELOG.md
roles/bitrise-den/defaults/main.yml
roles/profiles/files/bitrise_profile

[SVC-0] chore(den): new release

---

CHANGELOG.md
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile

[IN-2700] Update Homebrew Core and Cask commit ID

---

CHANGELOG.md
roles/baseos/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-2758] set timezone to GMT

---

CHANGELOG.md
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile

[IN-2745] Update homebrew

---

CHANGELOG.md
roles/flutter/tasks/main.yml
roles/flutter/templates/.profile.j2
roles/profiles/files/bashrc
roles/profiles/files/bitrise_profile
roles/profiles/files/zshrc

[IN-2762] Fix env paths

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ruby-gems/tasks/main.yml

[IN-2797] fix(ruby): change .ruby-version remove order

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/xcode/files/enable_accessibility.sh

[IN-2718] feat(xcode-helper): add accessibility privileges

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ruby-gems/tasks/main.yml

[IN-2797] fix(ruby-gems): fix ruby version

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/xcode/files/enable_accessibility.sh

[IN-2718] feat(xcode): add helper to accessibility whitelist

---

CHANGELOG.md
roles/profiles/files/bitrise_profile
roles/ruby-gems/tasks/main.yml
roles/xcode/tasks/check.yml
roles/xcode/tasks/dir_check.yml
roles/xcode/tasks/main.yml

[IN-2669] feat(xcode): add correctness checks

---

CHANGELOG.md
roles/bitrise-cli/defaults/main.yml
roles/profiles/files/bitrise_profile

[IN-2808] chore(bitrise-cli): Update Bitrise CLI to 1.47.1

---

CHANGELOG.md
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile

[IN-2779] chore(brew): Update homebrew core and homebrew cask

---

CHANGELOG.md
roles/bitrise-den/defaults/main.yml
roles/profiles/files/bitrise_profile

[SVC-1314] feat(den): release v1.30.0

---

CHANGELOG.md
roles/brew/tasks/main.yml
roles/profiles/files/bitrise_profile

[IN-2779] chore(brew): install haxm on every stack

---

CHANGELOG.md
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile

[IN-2845] chore(brew): update brew repo mirrors

---

CHANGELOG.md
roles/android/defaults/main.yml
roles/flutter/defaults/main.yml
roles/profiles/files/bitrise_profile

Flutter 2.2.3
Android commandline tools 7302050
Android NDK 21e
Android build tools 30.0.1 - 30.0.3

Version updates:

---

CHANGELOG.md
_scripts/install_linters.sh
bitrise.yml
roles/profiles/files/bitrise_profile

[IN-2861] chore(ci): update linter installs

---

CHANGELOG.md
roles/brew-repos-fix/vars/main.yml
roles/profiles/files/bitrise_profile

- [ *] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ *] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

[IN-3578] Updated brew core and cask
